name: odev7
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
  
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  assets:
    - database/todos.sqlite


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
